
sonar.projectName=My Test Project
sonar.projectVersion=1.0.0
sonar.projectKey=test-workflow-catalog

sonar.scm.provider=git

sonar.python.version=3.9


sonar.branch.name=develop

sonar.python.coverage.reportPaths=python-demo/coverage.xml
sonar.python.xunit.reportPaths=python-demo/pytest-report.xml

sonar.sources=python-demo/src
sonar.tests=python-demo/tests

