name: Python Tests

on:
  push:

jobs:
  python-test:
    runs-on: self-hosted
    container: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.11"
          architecture: x64

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox
        working-directory: python-demo

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            python-demo/coverage.xml
            python-demo/pytest-report.xml
